name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - "**"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Hello world
        run: echo Hello World !
