name: Contributors Generate

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  Runner:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install git-contributor
        run: npm i git-contributor -D

      - name: Append contributors to the last commit
        run: |
          npm run contributors
          git add README.md
          git config --global user.name ${{ github.event.head_commit.author.name }}
          git config --global user.email ${{ github.event.head_commit.author.email }}
          git commit --amend --no-edit

      - name: Push to master branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: main
          build_dir: './.'
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
